### ISSUE TITLE
Script API, i.e. add editor auto-complete

### ISSUE THREAD

**Issue by aglitchman** [thejustinwalsh/defold-xmath#1]
Thanks for the extension!

It would be great to add *.script_api files to have auto-complete in the editor.

Docs: https://defold.com/manuals/extensions-script-api/

**Comment by thejustinwalsh** [comment]
Agreed! Need to get back on this and generate typings for ts-defold as well.

**Comment by thejustinwalsh** [comment]
@aglitchman I took a stab at this last year, got overwhelmed with the amount of data entry it was going to be, and gave up.

I have type generators that generate TypeScript types from defold documentation and script_api files, so now I feel like I should make tooling that takes TypeScript types and goes the other way. That project sounds more interesting than hand crafting the types. 

Also, I might be able to get ChatGPT or Copilot to do it for me, and that sounds fun!

**Comment by aglitchman** [comment]
> @aglitchman I took a stab at this last year, got overwhelmed with the amount of data entry it was going to be, and gave up.

I planned to write the script api by myself and make a pull request, but I also gave up 😀 Because of the large amount of monotonous work.

**Comment by thejustinwalsh** [comment]
@aglitchman Thanks to @thinknathan, this is now merged and good to go!
Thanks again @thinknathan!
